feat: add branch name validation

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -1,2 +1,9 @@
+branch=$(git branch | grep '*' | sed 's/* //')
+
+if [[ "$branch" = "main" || "$branch" = "develop" ]]; then
+echo "You can't commit directly to 'main' or 'develop' branch. Please create your own branch and use PR"
+exit 1
+fi
+
 npm run lint
 npm run format:fix
